<div class="benefits-bar">
    <div class="container">
        <div class="benefit-item">
            <i class="icon">local_shipping</i>
            <span><strong>Dividimos o frete</strong> em compras acima de R$3 mil</span>
        </div>
        <div class="benefit-item">
            <i class="icon">credit_score</i>
            <span><strong>Parcelamos em 2x sem juros</strong>  em compras acima de R$2 mil</span>
        </div>
        <div class="benefit-item">
            <i class="icon">attach_money</i>
            <span><strong>3% de desconto!</strong>  Para pagamento via Pix ou Boleto</span>
        </div>
    </div>
</div>