<div class="contact-info">

    <span class="icon">call</span>
    <p><strong>Entre em</strong><br>
        contato</p>

    <ul class="list-contacts">
        <li class="contact-item">
            <i class="icon">phone_iphone</i>
            <dv class="info">
                <strong>Telefone:</strong><br>
                <span>(11) 1234-5678</span>
            </dv>
        </li>
        <li class="contact-item">
            <i class="icon">mail</i>
            <div class="info">
                <strong>Email:</strong><br>
                <span>contato@exemplo.com</span>
            </div>
        </li>
        <li class="contact-item">
            <i class="icon">location_on</i>
            <div class="info">
                <strong>Endereço:</strong><br>
                <span>Rua Exemplo, 123, São Paulo - SP</span>
            </div>
        </li>
    </ul>
</div>